# Generated by Django 2.0.7 on 2019-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management_main', '0002_auto_20191202_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=100000),
            preserve_default=False,
        ),
    ]
