# Generated by Django 2.0.7 on 2019-12-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management_main', '0004_auto_20191208_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionday',
            name='sum',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=100000),
        ),
    ]
